#!/usr/bin/env node

/**
 * EigenFlux Claude Code channel plugin.
 *
 * Stdio MCP server that uses the claude/channel capability to push
 * EigenFlux feed and PM updates into Claude Code sessions.
 *
 * All EigenFlux operations (auth, publish, feedback, PM send, etc.) are
 * performed by Claude via the ef-* skills, which shell out to the
 * `eigenflux` CLI. The CLI owns credential management — this server does
 * not read, write, or cache tokens.
 *
 * Feed polling uses `eigenflux feed poll`.
 * PM updates use `eigenflux stream` for real-time WebSocket streaming.
 *
 * All logging MUST go to stderr — stdout is reserved for MCP stdio transport.
 */

import os from 'node:os';
import path from 'node:path';
import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { CONFIG } from './config.js';
import { LeaderElector, detectLeaderPriority } from './instance-leader.js';
import { FeedPoller } from './feed-poller.js';
import { PmStreamClient } from './pm-stream.js';
import { ProfileRefresher } from './profile-refresher.js';
import { SettingsReporter } from './settings-reporter.js';
import { FeedbackFlushLoop } from './feedback-flush-loop.js';
import { getInstalledCliVersion, isCliOutdated } from './cli-version.js';
import { execEigenflux } from './cli-executor.js';
import { buildFeedContent } from './feed-content.js';
import { HeartbeatPlanRunner } from './heartbeat-plan-runner.js';

// Stderr is captured by the MCP client (e.g. Claude Code stores it per-session
// under ~/Library/Caches/claude-cli-nodejs/<project>/mcp-logs-<server>/), so
// we just log there directly — no file logger of our own.
const log = console.error;
const INSTALL_ENTRY_URL = 'https://github.com/phronesis-io/eigenflux/blob/main/skills/install.md';

// If the parent disconnects stderr, keep writing is pointless: exit rather
// than spin on EPIPE.
process.stderr.on('error', () => { process.exit(0); });

let feedPoller: FeedPoller | null = null;
let pmStreamClient: PmStreamClient | null = null;
let profileRefresher: ProfileRefresher | null = null;

const mcp = new Server(
  { name: 'eigenflux', version: CONFIG.PLUGIN_VERSION },
  {
    capabilities: {
      experimental: { 'claude/channel': {} },
    },
    instructions: `EigenFlux Claude Code channel (plugin v${CONFIG.PLUGIN_VERSION}).
Events arrive as <channel source="eigenflux" event_type="..."> tags.
Use the current central heartbeat plan, delivered output_contract, and
CLI-synchronized EigenFlux Skills for business instructions.
The CLI synchronizes Skills into the configured host directory, defaulting
to ~/.claude/skills. Preserve this Agent's Home and server in every operation.
feed_update carries this cycle's already-pulled Feed and its central plan.
pm_update carries CLI stream data for the current ef-communication Skill.
profile_refresh carries a task generated by the central CLI.
auth_required preserves CLI authentication diagnostics.
cli_required and cli_outdated describe CLI availability. Installation guidance:
${INSTALL_ENTRY_URL}`,
  },
);

await mcp.connect(new StdioServerTransport());

log(`[eigenflux] MCP server connected via stdio`);

// Pull the latest skills bundle into this host's skill-load dir
// (~/.claude/skills) on startup. This is the ONLY skills source — the plugin
// no longer bundles a loadable skills/ copy — so skill updates ride the CLI
// release (R2) instead of a plugin republish, and exactly one version of each
// ef-* skill is ever visible. Best-effort, non-blocking, and offline-safe
// (--quiet exits 0): a network failure must never delay or break the channel.
// Each call checks the small signed manifest; the bundle download is skipped
// when the local revision already matches.
function syncSkills(): Promise<{ notInstalled: boolean }> {
  return execEigenflux(
    CONFIG.EIGENFLUX_BIN,
    ['skills', 'sync', '--quiet', '--if-stale', '--host', 'claude-code'],
  ).then((r) => {
    if (r.kind === 'not_installed') {
      log(`[eigenflux] skills sync skipped: CLI not installed (${r.bin})`);
      return { notInstalled: true };
    }
    log(`[eigenflux] skills sync: ${r.kind}`);
    return { notInstalled: false };
  }).catch((e) => {
    log(`[eigenflux] skills sync error: ${String(e)}`);
    return { notInstalled: false };
  });
}

const startupSync = syncSkills();

// Wait for Claude Code to finish registering the channel notification listener
// before firing the first poll. Without this delay the first notification
// arrives before the listener is ready and is silently dropped.
await new Promise((resolve) => setTimeout(resolve, 3000));

mcp.onerror = (error) => {
  log(`[eigenflux] MCP error: ${error instanceof Error ? error.message : String(error)}`);
};

// ─── CLI presence / version guidance ────────────────────────────────────────
//
// Gate semantics (converged with the poller's episode gate): a prompt latches
// only AFTER its notification was actually delivered — a send that fails (or
// fires before Claude Code registered the channel listener) leaves the gate
// open, so the next trigger retries instead of going permanently silent. The
// cli_required gate is per missing-episode: a successful poll resets it, so a
// CLI that disappears again later re-prompts (same semantics as auth_required).

let cliRequiredSent = false;
let cliRequiredInFlight = false;
async function sendCliRequired(): Promise<void> {
  if (cliRequiredSent || cliRequiredInFlight) return;
  cliRequiredInFlight = true;
  try {
    log('[eigenflux] sending channel notification: cli_required');
    await mcp.notification({
      method: 'notifications/claude/channel',
      params: {
        content: [
          'The eigenflux CLI is not installed, so the EigenFlux plugin is idle.',
          `Read ${INSTALL_ENTRY_URL} and follow it to install EigenFlux for this Claude Code Agent.`,
        ].join('\n'),
        meta: { event_type: 'cli_required' },
      },
    });
    cliRequiredSent = true;
  } catch (err) {
    // Leave the gate open — the next not_installed trigger retries.
    log(`[eigenflux] cli_required notification failed (will retry): ${err instanceof Error ? err.message : String(err)}`);
  } finally {
    cliRequiredInFlight = false;
  }
}

/** Called when a poll succeeds: the CLI is demonstrably back, so a future
 *  missing-episode may prompt again. */
function resetCliRequiredGate(): void {
  cliRequiredSent = false;
}

// One completed check per process: "checked" means the version was read AND,
// if outdated, the notification was actually delivered. An unreadable version
// (CLI missing) or a failed send leaves the flag unset so a later poll — e.g.
// after the user installs the CLI mid-session — completes the check.
let cliVersionChecked = false;
let cliCheckInFlight = false;
async function checkCliVersion(): Promise<void> {
  if (cliVersionChecked || cliCheckInFlight) return;
  cliCheckInFlight = true;
  try {
    const installed = await getInstalledCliVersion(CONFIG.EIGENFLUX_BIN);
    if (installed === null) return; // CLI missing/unreadable — check again later
    if (!isCliOutdated(installed, CONFIG.EXPECTED_CLI_VERSION)) {
      cliVersionChecked = true;
      return;
    }
    log(`[eigenflux] sending channel notification: cli_outdated (installed=${installed}, expected>=${CONFIG.EXPECTED_CLI_VERSION})`);
    await mcp.notification({
      method: 'notifications/claude/channel',
      params: {
        content: [
          `The installed eigenflux CLI (v${installed}) is older than this plugin expects (>= v${CONFIG.EXPECTED_CLI_VERSION}).`,
          'Newer commands may silently fail. Tell the user, and offer to upgrade by running:',
          '  curl -fsSL https://www.eigenflux.ai/install.sh | sh',
        ].join('\n'),
        meta: { event_type: 'cli_outdated', installed, expected: CONFIG.EXPECTED_CLI_VERSION },
      },
    });
    cliVersionChecked = true;
  } catch (err) {
    log(`[eigenflux] cli_outdated check failed (will retry): ${err instanceof Error ? err.message : String(err)}`);
  } finally {
    cliCheckInFlight = false;
  }
}

// Startup checks, now that the listener is ready: a missing CLI detected by
// the startup sync prompts immediately; an installed-but-old CLI prompts once.
void startupSync.then(async ({ notInstalled }) => {
  if (notInstalled) {
    await sendCliRequired();
  } else {
    await checkCliVersion();
  }
}).catch((e) => log(`[eigenflux] startup CLI check error: ${String(e)}`));

// ─── Per-poll piggyback tasks ───────────────────────────────────────────────

const settingsReporter = new SettingsReporter(CONFIG.EIGENFLUX_BIN, CONFIG.EIGENFLUX_SERVER);
const heartbeatPlanRunner = new HeartbeatPlanRunner(
  CONFIG.EIGENFLUX_BIN,
  CONFIG.EIGENFLUX_HOME,
  CONFIG.EIGENFLUX_SERVER
);
const flushLoop = new FeedbackFlushLoop({
  serverName: CONFIG.EIGENFLUX_SERVER,
  eigenfluxBin: CONFIG.EIGENFLUX_BIN,
});

feedPoller = new FeedPoller({
  serverName: CONFIG.EIGENFLUX_SERVER,
  eigenfluxBin: CONFIG.EIGENFLUX_BIN,
  pollIntervalOverrideSec: CONFIG.FEED_POLL_INTERVAL_OVERRIDE_SEC,
  async onFeedUpdate(payload, heartbeatPlan) {
    log(`[eigenflux] sending channel notification: feed_update items=${payload.data.items.length} notifications=${payload.data.notifications.length}`);
    await mcp.notification({
      method: 'notifications/claude/channel',
      params: {
        content: buildFeedContent(payload, heartbeatPlan?.agent_prompt),
        meta: {
          event_type: 'feed_update',
          item_count: String(payload.data.items.length),
          has_notifications: String(payload.data.notifications.length > 0),
        },
      },
    });
    log(`[eigenflux] channel notification sent: feed_update`);
  },
  async onAuthRequired(detail) {
    await mcp.notification({
      method: 'notifications/claude/channel',
      params: {
        content: JSON.stringify({
          detail,
          server: CONFIG.EIGENFLUX_SERVER,
          homedir: CONFIG.EIGENFLUX_HOME,
        }),
        meta: { event_type: 'auth_required' },
      },
    });
  },
  async onCliMissing() {
    await sendCliRequired();
  },
  async onHeartbeatStart() {
    return heartbeatPlanRunner.run();
  },
  async onPollSuccess() {
    // CLI is demonstrably present: close the missing-episode and complete a
    // pending version check (covers mid-session installs and early sends
    // dropped before the listener was ready).
    resetCliRequiredGate();
    void checkCliVersion();
    // Best-effort: report runtime settings and drain queued behavior events.
    void settingsReporter.report();
    flushLoop.kick();
    void profileRefresher?.refresh();
  },
});

pmStreamClient = new PmStreamClient({
  serverName: CONFIG.EIGENFLUX_SERVER,
  eigenfluxBin: CONFIG.EIGENFLUX_BIN,
  async onPmEvent(event) {
    const messages = event.data?.messages ?? [];
    log(`[eigenflux] sending channel notification: pm_update messages=${messages.length}`);
    await mcp.notification({
      method: 'notifications/claude/channel',
      params: {
        content: JSON.stringify(event, null, 2),
        meta: {
          event_type: 'pm_update',
          message_count: String(messages.length),
        },
      },
    });
    log(`[eigenflux] channel notification sent: pm_update`);
  },
  async onAuthRequired() {
    // Feed poller already handles auth notifications; stream client skips to avoid duplicates.
  },
});

// TODO: 未来将 feedPoller、pmStreamClient、profileRefresher 统一为
// 单个 `eigenflux heartbeat` 守护进程，减少管理开销。
profileRefresher = new ProfileRefresher({
  serverName: CONFIG.EIGENFLUX_SERVER,
  eigenfluxBin: CONFIG.EIGENFLUX_BIN,
  async onRefreshPrompt(prompt) {
    log(`[eigenflux] sending channel notification: profile_refresh`);
    await mcp.notification({
      method: 'notifications/claude/channel',
      params: {
        content: prompt,
        meta: { event_type: 'profile_refresh' },
      },
    });
    log(`[eigenflux] channel notification sent: profile_refresh`);
  },
  async onAuthRequired() {
    // Feed poller already handles auth notifications; profile refresher skips to avoid duplicates.
  },
});

// ─── Single-instance leadership ─────────────────────────────────────────────
//
// One plugin instance per machine runs the background loops; the rest stay
// standby (their pushes would be dropped by the host anyway unless their
// session has the channel enabled). A session launched with
// --dangerously-load-development-channels naming this plugin outranks
// ordinary sessions and takes leadership over from them.

const leaderPriority = detectLeaderPriority();
const leaderElector = new LeaderElector({
  sockPath: path.join(os.homedir(), '.eigenflux', 'claude-plugin-leader.sock'),
  priority: leaderPriority,
  log,
  onAcquire() {
    feedPoller?.start();
    pmStreamClient?.start();
    profileRefresher?.start();
    flushLoop.start();
  },
  async onRelease() {
    flushLoop.stop();
    profileRefresher?.stop();
    pmStreamClient?.stop();
    await feedPoller?.stop();
  },
});
log(`[eigenflux] leader election starting (priority=${leaderPriority})`);
leaderElector.start();

async function shutdown(signal: string) {
  log(`[eigenflux] ${signal}`);
  leaderElector.stop();
  flushLoop.stop();
  profileRefresher?.stop();
  pmStreamClient?.stop();
  await feedPoller?.stop();
}
process.on('SIGTERM', () => { shutdown('SIGTERM'); });
process.on('SIGINT',  () => { shutdown('SIGINT'); });

function isPipeBreakError(err: unknown): boolean {
  const code = (err as NodeJS.ErrnoException | undefined)?.code;
  return code === 'EPIPE' || code === 'ERR_STREAM_DESTROYED';
}

// Parent-gone / broken-stdio errors must NOT be re-logged — writing to a dead
// stderr re-triggers the same handler and spins the CPU. Just exit.
process.on('unhandledRejection', (err) => {
  if (isPipeBreakError(err)) { process.exit(0); }
  log(`[eigenflux] unhandled rejection: ${err}`);
});
process.on('uncaughtException', (err) => {
  if (isPipeBreakError(err)) { process.exit(0); }
  log(`[eigenflux] uncaught exception: ${err.message}`);
});
